default: &default
  adapter: postgresql
  encoding: unicode
  database: hex_bot_development
  host: localhost
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: hex_bot_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
